/**
 * GitHub Configuration
 * Auto-generated by GitHub Actions - DO NOT EDIT MANUALLY
 * Last updated: 2026-02-03 06:44:08 UTC
 */

export const GITHUB_CONFIG = {
    username: 'projektcode',

    pinnedRepos: [
        {
            name: "Lyuze-3.0",
            description: "Discord bot using Discord.Net",
            url: "https://github.com/ProjektCode/Lyuze-3.0",
            language: "C#"
        },
        {
            name: "byte86",
            description: "School 2D Game Dev Project",
            url: "https://github.com/ProjektCode/byte86",
            language: "C#"
        },
        {
            name: "Crimson",
            description: "Crimson theme insipired by Catppuccin",
            url: "https://github.com/ProjektCode/Crimson",
            language: "CSS"
        },
        {
            name: "Projekt-Links",
            description: "Small static website to host some of my links. Site was created with AI as to see how it could work.",
            url: "https://github.com/ProjektCode/Projekt-Links",
            language: "JavaScript"
        },
        {
            name: "wuwa-api",
            description: "Wuthering Waves Unofficial API | Click the website below to see the docs or if you want to see some nice modern looking docs visit https://wuwa.projektcode.com/docs",
            url: "https://github.com/ProjektCode/wuwa-api",
            language: "TypeScript"
        },
        {
            name: "TSR_Modpack_Datapack",
            description: "1.21.1 custom Minecraft Datapack. For custom Modpack.",
            url: "https://github.com/ProjektCode/TSR_Modpack_Datapack",
            language: "mcfunction"
        },
    ]
};
