/**
 * GitHub Configuration
 * Auto-generated by GitHub Actions - DO NOT EDIT MANUALLY
 * Last updated: 2026-01-10 20:21:48 UTC
 */

export const GITHUB_CONFIG = {
    username: 'projektcode',

    pinnedRepos: [
        {
            name: "Lyuze-3.0",
            description: "Discord bot using Discord.Net",
            url: "https://github.com/ProjektCode/Lyuze-3.0",
            language: "C#"
        },
        {
            name: "byte86",
            description: "School 2D Game Dev Project",
            url: "https://github.com/ProjektCode/byte86",
            language: "C#"
        },
        {
            name: "Crimson",
            description: "Crimson theme insipired by Catppuccin",
            url: "https://github.com/ProjektCode/Crimson",
            language: "CSS"
        },
    ]
};
